version: 2

sources:
  - name: raw_ecommerce
    database: automated-e-commerce-financial
    schema: raw_ecommerce
    tables:
      - name: raw_orders
      - name: raw_customers
      - name: raw_order_items
      - name: raw_products